# Generated by Django 5.1.11 on 2025-08-25 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('is_bulk', models.BooleanField(default=False)),
                ('measure_unit', models.CharField(default='unit', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'valid_from'], name='catalog_pri_product_57390e_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'currency', 'valid_from'), name='uq_price_start')],
            },
        ),
    ]
